/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class config {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected config(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_config(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBoolean(String key, boolean val) {
    SphinxBaseJNI.config_setBoolean(swigCPtr, this, key, val);
  }

  public void setInt(String key, int val) {
    SphinxBaseJNI.config_setInt(swigCPtr, this, key, val);
  }

  public void setFloat(String key, double val) {
    SphinxBaseJNI.config_setFloat(swigCPtr, this, key, val);
  }

  public void setString(String key, String val) {
    SphinxBaseJNI.config_setString(swigCPtr, this, key, val);
  }

  public void setStringExtra(String key, String val) {
    SphinxBaseJNI.config_setStringExtra(swigCPtr, this, key, val);
  }

  public boolean exists(String key) {
    return SphinxBaseJNI.config_exists(swigCPtr, this, key);
  }

  public boolean getBoolean(String key) {
    return SphinxBaseJNI.config_getBoolean(swigCPtr, this, key);
  }

  public int getInt(String key) {
    return SphinxBaseJNI.config_getInt(swigCPtr, this, key);
  }

  public double getFloat(String key) {
    return SphinxBaseJNI.config_getFloat(swigCPtr, this, key);
  }

  public String getString(String key) {
    return SphinxBaseJNI.config_getString(swigCPtr, this, key);
  }

}
