/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class frontEnd {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected frontEnd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(frontEnd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_frontEnd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public frontEnd() {
    this(SphinxBaseJNI.new_frontEnd(), true);
  }

  public int outputSize() {
    return SphinxBaseJNI.frontEnd_outputSize(swigCPtr, this);
  }

  public int processUtt(String spch, long nsamps, SWIGTYPE_p_p_p_mfcc_t cep_block) {
    return SphinxBaseJNI.frontEnd_processUtt(swigCPtr, this, spch, nsamps, SWIGTYPE_p_p_p_mfcc_t.getCPtr(cep_block));
  }

}
