/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class fsgModel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected fsgModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fsgModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_fsgModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public fsgModel(String name, logMath logmath, float lw, int n) {
    this(SphinxBaseJNI.new_fsgModel__SWIG_0(name, logMath.getCPtr(logmath), logmath, lw, n), true);
  }

  public fsgModel(String path, logMath logmath, float lw) {
    this(SphinxBaseJNI.new_fsgModel__SWIG_1(path, logMath.getCPtr(logmath), logmath, lw), true);
  }

  public int wordId(String word) {
    return SphinxBaseJNI.fsgModel_wordId(swigCPtr, this, word);
  }

  public int wordAdd(String word) {
    return SphinxBaseJNI.fsgModel_wordAdd(swigCPtr, this, word);
  }

  public void transAdd(int src, int dst, int logp, int wid) {
    SphinxBaseJNI.fsgModel_transAdd(swigCPtr, this, src, dst, logp, wid);
  }

  public int nullTransAdd(int src, int dst, int logp) {
    return SphinxBaseJNI.fsgModel_nullTransAdd(swigCPtr, this, src, dst, logp);
  }

  public int tagTransAdd(int src, int dst, int logp, int wid) {
    return SphinxBaseJNI.fsgModel_tagTransAdd(swigCPtr, this, src, dst, logp, wid);
  }

  public int addSilence(String silword, int state, float silprob) {
    return SphinxBaseJNI.fsgModel_addSilence(swigCPtr, this, silword, state, silprob);
  }

  public int addAlt(String baseword, String altword) {
    return SphinxBaseJNI.fsgModel_addAlt(swigCPtr, this, baseword, altword);
  }

  public void writefile(String path) {
    SphinxBaseJNI.fsgModel_writefile(swigCPtr, this, path);
  }

}
