/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class hypothesis {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected hypothesis(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(hypothesis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_hypothesis(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHypstr(String value) {
    PocketSphinxJNI.hypothesis_hypstr_set(swigCPtr, this, value);
  }

  public String getHypstr() {
    return PocketSphinxJNI.hypothesis_hypstr_get(swigCPtr, this);
  }

  public void setBestScore(int value) {
    PocketSphinxJNI.hypothesis_bestScore_set(swigCPtr, this, value);
  }

  public int getBestScore() {
    return PocketSphinxJNI.hypothesis_bestScore_get(swigCPtr, this);
  }

  public void setProb(int value) {
    PocketSphinxJNI.hypothesis_prob_set(swigCPtr, this, value);
  }

  public int getProb() {
    return PocketSphinxJNI.hypothesis_prob_get(swigCPtr, this);
  }

  public hypothesis(String hypstr, int best_score, int prob) {
    this(PocketSphinxJNI.new_hypothesis(hypstr, best_score, prob), true);
  }

}
