/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class jsgf implements Iterable<jsgfRule> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected jsgf(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(jsgf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_jsgf(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public jsgfIterator iterator() {
    long cPtr = SphinxBaseJNI.jsgf_iterator(swigCPtr, this);
    return (cPtr == 0) ? null : new jsgfIterator(cPtr, true);
  }

  public jsgf(String path) {
    this(SphinxBaseJNI.new_jsgf(path), true);
  }

  public String getName() {
    return SphinxBaseJNI.jsgf_getName(swigCPtr, this);
  }

  public jsgfRule getRule(String name) {
    long cPtr = SphinxBaseJNI.jsgf_getRule(swigCPtr, this, name);
    return (cPtr == 0) ? null : new jsgfRule(cPtr, false);
  }

  public fsgModel buildFsg(jsgfRule rule, logMath logmath, float lw) {
    long cPtr = SphinxBaseJNI.jsgf_buildFsg(swigCPtr, this, jsgfRule.getCPtr(rule), rule, logMath.getCPtr(logmath), logmath, lw);
    return (cPtr == 0) ? null : new fsgModel(cPtr, false);
  }

}
