/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class jsgfIterator implements java.util.Iterator<jsgfRule> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected jsgfIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(jsgfIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_jsgfIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void remove() {
    throw new UnsupportedOperationException();
  }

  public jsgfIterator(SWIGTYPE_p_void ptr) {
    this(SphinxBaseJNI.new_jsgfIterator(SWIGTYPE_p_void.getCPtr(ptr)), true);
  }

  public jsgfRule next() {
    long cPtr = SphinxBaseJNI.jsgfIterator_next(swigCPtr, this);
    return (cPtr == 0) ? null : new jsgfRule(cPtr, true);
  }

  public boolean hasNext() {
    return SphinxBaseJNI.jsgfIterator_hasNext(swigCPtr, this);
  }

}
