/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class jsgfRule {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected jsgfRule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(jsgfRule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_jsgfRule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public jsgfRule() {
    this(SphinxBaseJNI.new_jsgfRule(), true);
  }

  public static jsgfRule fromIter(SWIGTYPE_p_void itor) {
    long cPtr = SphinxBaseJNI.jsgfRule_fromIter(SWIGTYPE_p_void.getCPtr(itor));
    return (cPtr == 0) ? null : new jsgfRule(cPtr, false);
  }

  public String getName() {
    return SphinxBaseJNI.jsgfRule_getName(swigCPtr, this);
  }

  public boolean isPublic() {
    return SphinxBaseJNI.jsgfRule_isPublic(swigCPtr, this);
  }

}
