/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class lattice {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected lattice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lattice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_lattice(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public lattice(String path) {
    this(PocketSphinxJNI.new_lattice__SWIG_0(path), true);
  }

  public lattice(decoder decoder, String path) {
    this(PocketSphinxJNI.new_lattice__SWIG_1(decoder.getCPtr(decoder), decoder, path), true);
  }

  public void write(String path) {
    PocketSphinxJNI.lattice_write(swigCPtr, this, path);
  }

  public void writeHtk(String path) {
    PocketSphinxJNI.lattice_writeHtk(swigCPtr, this, path);
  }

}
