/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class logMath {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected logMath(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(logMath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_logMath(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public logMath() {
    this(SphinxBaseJNI.new_logMath(), true);
  }

  public double exp(int prob) {
    return SphinxBaseJNI.logMath_exp(swigCPtr, this, prob);
  }

}
