/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class nBest {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected nBest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nBest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_nBest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHypstr(String value) {
    PocketSphinxJNI.nBest_hypstr_set(swigCPtr, this, value);
  }

  public String getHypstr() {
    return PocketSphinxJNI.nBest_hypstr_get(swigCPtr, this);
  }

  public void setScore(int value) {
    PocketSphinxJNI.nBest_score_set(swigCPtr, this, value);
  }

  public int getScore() {
    return PocketSphinxJNI.nBest_score_get(swigCPtr, this);
  }

  public static nBest fromIter(SWIGTYPE_p_void itor) {
    long cPtr = PocketSphinxJNI.nBest_fromIter(SWIGTYPE_p_void.getCPtr(itor));
    return (cPtr == 0) ? null : new nBest(cPtr, false);
  }

  public hypothesis hyp() {
    long cPtr = PocketSphinxJNI.nBest_hyp(swigCPtr, this);
    return (cPtr == 0) ? null : new hypothesis(cPtr, true);
  }

  public nBest() {
    this(PocketSphinxJNI.new_nBest(), true);
  }

}
