/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class nBestIterator implements java.util.Iterator<nBest> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected nBestIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nBestIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_nBestIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void remove() {
    throw new UnsupportedOperationException();
  }

  public nBestIterator(SWIGTYPE_p_void ptr) {
    this(PocketSphinxJNI.new_nBestIterator(SWIGTYPE_p_void.getCPtr(ptr)), true);
  }

  public nBest next() {
    long cPtr = PocketSphinxJNI.nBestIterator_next(swigCPtr, this);
    return (cPtr == 0) ? null : new nBest(cPtr, true);
  }

  public boolean hasNext() {
    return PocketSphinxJNI.nBestIterator_hasNext(swigCPtr, this);
  }

}
