/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class nBestList implements Iterable<nBest> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nBestList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nBestList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_nBestList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public nBestIterator iterator() {
    long cPtr = PocketSphinxJNI.nBestList_iterator(swigCPtr, this);
    return (cPtr == 0) ? null : new nBestIterator(cPtr, true);
  }

}
