/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class nGramModelSet implements Iterable<nGramModel> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected nGramModelSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nGramModelSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_nGramModelSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public nGramModelSetIterator iterator() {
    long cPtr = SphinxBaseJNI.nGramModelSet_iterator(swigCPtr, this);
    return (cPtr == 0) ? null : new nGramModelSetIterator(cPtr, true);
  }

  public nGramModelSet(config config, logMath logmath, String path) {
    this(SphinxBaseJNI.new_nGramModelSet(config.getCPtr(config), config, logMath.getCPtr(logmath), logmath, path), true);
  }

  public int count() {
    return SphinxBaseJNI.nGramModelSet_count(swigCPtr, this);
  }

  public nGramModel add(nGramModel model, String name, float weight, boolean reuse_widmap) {
    long cPtr = SphinxBaseJNI.nGramModelSet_add(swigCPtr, this, nGramModel.getCPtr(model), model, name, weight, reuse_widmap);
    return (cPtr == 0) ? null : new nGramModel(cPtr, false);
  }

  public nGramModel select(String name) {
    long cPtr = SphinxBaseJNI.nGramModelSet_select(swigCPtr, this, name);
    return (cPtr == 0) ? null : new nGramModel(cPtr, false);
  }

  public nGramModel lookup(String name) {
    long cPtr = SphinxBaseJNI.nGramModelSet_lookup(swigCPtr, this, name);
    return (cPtr == 0) ? null : new nGramModel(cPtr, false);
  }

  public String current() {
    return SphinxBaseJNI.nGramModelSet_current(swigCPtr, this);
  }

}
