/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class nGramModel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected nGramModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nGramModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_nGramModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static nGramModel fromIter(SWIGTYPE_p_void itor) {
    long cPtr = SphinxBaseJNI.nGramModel_fromIter(SWIGTYPE_p_void.getCPtr(itor));
    return (cPtr == 0) ? null : new nGramModel(cPtr, false);
  }

  public nGramModel(String path) {
    this(SphinxBaseJNI.new_nGramModel__SWIG_0(path), true);
  }

  public nGramModel(config config, logMath logmath, String path) {
    this(SphinxBaseJNI.new_nGramModel__SWIG_1(config.getCPtr(config), config, logMath.getCPtr(logmath), logmath, path), true);
  }

  public void write(String path, int ftype) {
    SphinxBaseJNI.nGramModel_write(swigCPtr, this, path, ftype);
  }

  public int strToType(String str) {
    return SphinxBaseJNI.nGramModel_strToType(swigCPtr, this, str);
  }

  public String typeToStr(int type) {
    return SphinxBaseJNI.nGramModel_typeToStr(swigCPtr, this, type);
  }

  public void casefold(int kase) {
    SphinxBaseJNI.nGramModel_casefold(swigCPtr, this, kase);
  }

  public int size() {
    return SphinxBaseJNI.nGramModel_size(swigCPtr, this);
  }

  public int addWord(String word, float weight) {
    return SphinxBaseJNI.nGramModel_addWord(swigCPtr, this, word, weight);
  }

  public int prob(String[] n) {
    return SphinxBaseJNI.nGramModel_prob(swigCPtr, this, n);
  }

}
