/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class segmentIterator implements java.util.Iterator<segment> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected segmentIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(segmentIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_segmentIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void remove() {
    throw new UnsupportedOperationException();
  }

  public segmentIterator(SWIGTYPE_p_void ptr) {
    this(PocketSphinxJNI.new_segmentIterator(SWIGTYPE_p_void.getCPtr(ptr)), true);
  }

  public segment next() {
    long cPtr = PocketSphinxJNI.segmentIterator_next(swigCPtr, this);
    return (cPtr == 0) ? null : new segment(cPtr, true);
  }

  public boolean hasNext() {
    return PocketSphinxJNI.segmentIterator_hasNext(swigCPtr, this);
  }

}
