/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class segment {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected segment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(segment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_segment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWord(String value) {
    PocketSphinxJNI.segment_word_set(swigCPtr, this, value);
  }

  public String getWord() {
    return PocketSphinxJNI.segment_word_get(swigCPtr, this);
  }

  public void setAscore(int value) {
    PocketSphinxJNI.segment_ascore_set(swigCPtr, this, value);
  }

  public int getAscore() {
    return PocketSphinxJNI.segment_ascore_get(swigCPtr, this);
  }

  public void setLscore(int value) {
    PocketSphinxJNI.segment_lscore_set(swigCPtr, this, value);
  }

  public int getLscore() {
    return PocketSphinxJNI.segment_lscore_get(swigCPtr, this);
  }

  public void setLback(int value) {
    PocketSphinxJNI.segment_lback_set(swigCPtr, this, value);
  }

  public int getLback() {
    return PocketSphinxJNI.segment_lback_get(swigCPtr, this);
  }

  public void setProb(int value) {
    PocketSphinxJNI.segment_prob_set(swigCPtr, this, value);
  }

  public int getProb() {
    return PocketSphinxJNI.segment_prob_get(swigCPtr, this);
  }

  public void setStartFrame(int value) {
    PocketSphinxJNI.segment_startFrame_set(swigCPtr, this, value);
  }

  public int getStartFrame() {
    return PocketSphinxJNI.segment_startFrame_get(swigCPtr, this);
  }

  public void setEndFrame(int value) {
    PocketSphinxJNI.segment_endFrame_set(swigCPtr, this, value);
  }

  public int getEndFrame() {
    return PocketSphinxJNI.segment_endFrame_get(swigCPtr, this);
  }

  public static segment fromIter(SWIGTYPE_p_void itor) {
    long cPtr = PocketSphinxJNI.segment_fromIter(SWIGTYPE_p_void.getCPtr(itor));
    return (cPtr == 0) ? null : new segment(cPtr, false);
  }

  public segment() {
    this(PocketSphinxJNI.new_segment(), true);
  }

}
