/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class segmentList implements Iterable<segment> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected segmentList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(segmentList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_segmentList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public segmentIterator iterator() {
    long cPtr = PocketSphinxJNI.segmentList_iterator(swigCPtr, this);
    return (cPtr == 0) ? null : new segmentIterator(cPtr, true);
  }

}
